// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldljobamskuimpufpkpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbGpvYmFtc2t1aW1wdWZwa3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTQ1MDQsImV4cCI6MjA1OTk3MDUwNH0.eVnNpTeZah3dD4-YymVXyVagKRgUbSEkSJkwxGaCR20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);